name: Deploy to Main (SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_CPANEL_ONTIME_CITY_MAIN_SSH_KEY }}

      - name: Add host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEV_CPANEL_ONTIME_CITY_MAIN_HOST }} >> ~/.ssh/known_hosts

      - name: SSH deploy
        run: |
          ssh ${{ secrets.DEV_CPANEL_ONTIME_CITY_MAIN_USER }}@${{ secrets.DEV_CPANEL_ONTIME_CITY_MAIN_HOST }} << 'EOF'
            cd /home/ontime-dev-cpanel/htdocs/dev.cpanel.ontime.city
            git pull origin main
            composer install --prefer-dist --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate
          EOF