name: Deploy to Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CPANEL_ONTIME_CITY_MAIN_SSH_KEY }}

      - name: Add Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.CPANEL_ONTIME_CITY_MAIN_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ${{ secrets.CPANEL_ONTIME_CITY_MAIN_USER }}@${{ secrets.CPANEL_ONTIME_CITY_MAIN_HOST }} << 'EOF'
            cd /home/ontime-cpanel/htdocs/cpanel.ontime.city

            git fetch origin
            git reset --hard origin/production

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
